### ISSUE TITLE
Copy/paste changes 00 to 20

### ISSUE THREAD

**Issue by hoensr** [chcg/NPP_HexEdit#24]
If I copy some hex from the HexEdit plugin to the clipboard and paste it somewhere else, "00" bytes are changed to "20".

![image](https://user-images.githubusercontent.com/7766044/72418568-60a2ab80-377b-11ea-8cec-44d51a5b6dd2.png)

![image](https://user-images.githubusercontent.com/7766044/72418626-77e19900-377b-11ea-9f83-bd9229a4f290.png)

![image](https://user-images.githubusercontent.com/7766044/72418667-9182e080-377b-11ea-8398-d001874b976c.png)

I use the newest HexEdtor 0.9.5.19 (2018-02-11) with Notepad++ 7.8.2.

**Comment by hoensr** [comment]
Also, if I copy not the hex digits, but something from the right-hand side, and paste it, an additional space character is appended. Shall I open a separate issue about this?

**Comment by zygimantus** [comment]
Related question: does HexEdit support copying the whole set of hex digits of a given text?

**Comment by kowitsch** [comment]
The same behaviour applies to the search dialog (ctrl-F). Hex values "30 00 35 00 35 00 33 00" can be searched for when entered manually into dialog box. 
![Notepad++ v7 8 6   (64-bit)_hex_find_(manually_entered)](https://user-images.githubusercontent.com/64707838/80891099-1a3d7200-8cc2-11ea-96e9-bc576f4f508d.PNG)
When selecting the same Hex values in the edit window, the dialog box shows 20 istead of 00 (30 20 35 20 35 20 33 20) and consequently doesn't find the desired values:
![Notepad++ v7 8 6   (64-bit)_hex_find_(marked_in_edit_area)](https://user-images.githubusercontent.com/64707838/80891204-de56dc80-8cc2-11ea-8c89-5010c6ed9927.PNG)

Debug info: Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : HexEditor.dll HTMLTag.dll mimeTools.dll NppConverter.dll NppExport.dll 
Using: HexEditor_0.9.6_x64.zip

**Comment by sploitsmith** [comment]
Added a similar [bug ](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11003)in Notepad++ as it has the same behaviour, and I suspect the bugs are related.

**Comment by sploitsmith** [comment]
So, further investigation. Seems it might be a scintilla "[feature](https://sourceforge.net/p/scintilla/bugs/1289/)" that was introduced in 2013. 
One [workaround ](https://superuser.com/questions/1480100/in-notepad-how-can-i-copy-a-lot-of-nulls-without-changing-it-to-a-space-on-a)for notepad++ suggests using the `Edit > Paste Special > Copy Binary Content` menu in notepadd++. 

![image](https://user-images.githubusercontent.com/13077204/148540797-ce3aaf03-f1b2-4c78-b8d8-b724adbb652a.png)

However, this menu isn't available in the Hex-Editor plugin.

So, I suggest the best fix for Hex-Editor is:
1) Enable the `paste special` menu
2) Just make use of the underlying notepad++ code to `copy binary content` rather than the standard copy/paste.

I would get involved and try and fix this, as it looks interesting, but I am not great at C++!

However, having a quick look, I think a good start would be in the [ModifyMenu.cpp](https://github.com/chcg/NPP_HexEdit/blob/master/HexEditor/src/misc/ModifyMenu.cpp) file. A custom Edit menu is created, which includes ` IDM_EDIT_COPY`. 

For starters, I think the menu should at least include `IDM_EDIT_COPY_BINARY`, `IDM_EDIT_CUT_BINARY` and `IDM_EDIT_PASTE_BINARY`, which would provide a workaround. 

Probably these should be used instead of the standard Copy, Cut, Paste.

**Comment by sploitsmith** [comment]
Ok. Got it working. Code is a bit janky though, so will clean it up first.

![image](https://user-images.githubusercontent.com/13077204/148624790-edb93db9-d9ac-4acc-b2e8-bb61d4f22f05.png)
![image](https://user-images.githubusercontent.com/13077204/148624860-a7a2ee67-7cb8-4ee7-8bf1-0009401c6963.png)

**Comment by sploitsmith** [comment]
I have done a pull request with a fix for this. 
![image](https://user-images.githubusercontent.com/13077204/148689977-a7beb4ca-f1d0-449c-b74c-57221ba480b5.png)

**Comment by hoensr** [comment]
Thank you very much!

**Comment by chcg** [comment]
PR from sploitsmith https://github.com/chcg/NPP_HexEdit/pull/62

**Comment by mirh** [comment]
"Copy binary content" doesn't work for me, and only the first byte of the selection gets pasted.

**Comment by sploitsmith** [comment]
Any more info or steps to reproduce?

**Comment by mirh** [comment]
Not really much?
Open any non-text file and click the button while selecting anything with 00 inside. 
Depending on what pasting action you then use, the string will either stop before the first 00 or after the last 00. 

N++ is 8.4.8 and the plugin is 0.9.12 if it can help.

**Comment by sploitsmith** [comment]
I am on a different machine right now. I can try and look later. Does ver 0.9.11 work for you? Or the version I forked?

**Comment by mirh** [comment]
There's no binary release there, and 0.9.11 is blacklisted on newer npp versions
